// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade.proto
//
// This file was manually written to match the output of protoc-gen-go v1.32.0.
// It uses the descriptorpb package to build file descriptor bytes at init time,
// avoiding the need to hand-encode protobuf wire-format descriptor bytes.

package proto

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/descriptorpb"
	goproto "google.golang.org/protobuf/proto"
)

const (
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
)

// ---------------------------------------------------------------------------
// Package-level state (populated by file_trade_proto_init via sync.Once)
// ---------------------------------------------------------------------------

var (
	file_trade_proto_rawDesc     []byte
	file_trade_proto_goTypes     = []interface{}{(*RiskRequest)(nil), (*RiskResponse)(nil), (*RiskRequest_HeadersEntry)(nil)}
	file_trade_proto_depIdxs     = []int32{0, 3, 2, -1, -1, -1} // msg0(RiskRequest).field3 → type2(HeadersEntry); msg1, msg2 have no deps
	file_trade_proto_initCalled  bool
	file_trade_proto_once        sync.Once
	file_trade_proto_desc        protoreflect.FileDescriptor
	file_trade_proto_msgDescs    [3]protoreflect.MessageDescriptor
)

// ---------------------------------------------------------------------------
// Message: RiskRequest
// ---------------------------------------------------------------------------

type RiskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string            `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Amount    float64           `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Headers   map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RiskRequest) Reset()         { *x = RiskRequest{} }
func (x *RiskRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RiskRequest) ProtoMessage()  {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := file_trade_proto_msgInfo(0)
	if mi != nil {
		return protoimpl.X.MessageStateOf(protoimpl.Pointer(x)).MessageInfo(mi).ProtoReflect()
	}
	return nil
}

func (x *RiskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RiskRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RiskRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// RiskRequest_HeadersEntry is the synthetic map-entry message for RiskRequest.Headers.
type RiskRequest_HeadersEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RiskRequest_HeadersEntry) Reset()         { *x = RiskRequest_HeadersEntry{} }
func (x *RiskRequest_HeadersEntry) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RiskRequest_HeadersEntry) ProtoMessage()  {}

func (x *RiskRequest_HeadersEntry) ProtoReflect() protoreflect.Message {
	mi := file_trade_proto_msgInfo(2)
	if mi != nil {
		return protoimpl.X.MessageStateOf(protoimpl.Pointer(x)).MessageInfo(mi).ProtoReflect()
	}
	return nil
}

func (x *RiskRequest_HeadersEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RiskRequest_HeadersEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ---------------------------------------------------------------------------
// Message: RiskResponse
// ---------------------------------------------------------------------------

type RiskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approved bool   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Service  string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *RiskResponse) Reset()         { *x = RiskResponse{} }
func (x *RiskResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *RiskResponse) ProtoMessage()  {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := file_trade_proto_msgInfo(1)
	if mi != nil {
		return protoimpl.X.MessageStateOf(protoimpl.Pointer(x)).MessageInfo(mi).ProtoReflect()
	}
	return nil
}

func (x *RiskResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *RiskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RiskResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// ---------------------------------------------------------------------------
// file_trade_proto_msgInfo – returns the *protoimpl.MessageInfo for message i
// ---------------------------------------------------------------------------

func file_trade_proto_msgInfo(i int) *protoimpl.MessageInfo {
	file_trade_proto_once.Do(file_trade_proto_init)
	if int(i) < len(file_trade_proto_msgDescs) {
		// Use MessageInfoOf to look up the info by Go reflect type.
		switch i {
		case 0:
			return protoimpl.X.MessageInfoOf((*RiskRequest)(nil))
		case 1:
			return protoimpl.X.MessageInfoOf((*RiskResponse)(nil))
		case 2:
			return protoimpl.X.MessageInfoOf((*RiskRequest_HeadersEntry)(nil))
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Descriptor builder – constructs a descriptorpb.FileDescriptorProto that
// mirrors the trade.proto schema, then marshals it to raw bytes.
// ---------------------------------------------------------------------------

func buildTradeFileDescriptorProto() *descriptorpb.FileDescriptorProto {
	labelOpt := descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL

	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("trade.proto"),
		Package: strPtr("trade"),
		Syntax:  strPtr("proto3"),
	}

	// ---- RiskRequest ----
	rrFields := []*descriptorpb.FieldDescriptorProto{
		{Name: strPtr("request_id"), Number: int32Ptr(1), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_STRING), Label: &labelOpt, JsonName: strPtr("requestId")},
		{Name: strPtr("amount"), Number: int32Ptr(2), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_DOUBLE), Label: &labelOpt, JsonName: strPtr("amount")},
		{Name: strPtr("headers"), Number: int32Ptr(3), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), Label: lblPtr(descriptorpb.FieldDescriptorProto_LABEL_REPEATED), TypeName: strPtr(".trade.RiskRequest.HeadersEntry"), JsonName: strPtr("headers")},
	}
	headersEntry := &descriptorpb.DescriptorProto{
		Name: strPtr("HeadersEntry"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: strPtr("key"), Number: int32Ptr(1), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_STRING), Label: &labelOpt, JsonName: strPtr("key")},
			{Name: strPtr("value"), Number: int32Ptr(2), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_STRING), Label: &labelOpt, JsonName: strPtr("value")},
		},
		Options: &descriptorpb.MessageOptions{MapEntry: boolPtr(true)},
	}
	riskReq := &descriptorpb.DescriptorProto{
		Name:       strPtr("RiskRequest"),
		Field:      rrFields,
		NestedType: []*descriptorpb.DescriptorProto{headersEntry},
	}

	// ---- RiskResponse ----
	riskResp := &descriptorpb.DescriptorProto{
		Name: strPtr("RiskResponse"),
		Field: []*descriptorpb.FieldDescriptorProto{
			{Name: strPtr("approved"), Number: int32Ptr(1), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_BOOL), Label: &labelOpt, JsonName: strPtr("approved")},
			{Name: strPtr("message"), Number: int32Ptr(2), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_STRING), Label: &labelOpt, JsonName: strPtr("message")},
			{Name: strPtr("service"), Number: int32Ptr(3), Type: typPtr(descriptorpb.FieldDescriptorProto_TYPE_STRING), Label: &labelOpt, JsonName: strPtr("service")},
		},
	}

	fd.MessageType = []*descriptorpb.DescriptorProto{riskReq, riskResp}

	// ---- Service: RiskCheck ----
	fd.Service = []*descriptorpb.ServiceDescriptorProto{
		{
			Name: strPtr("RiskCheck"),
			Method: []*descriptorpb.MethodDescriptorProto{
				{
					Name:       strPtr("CheckRisk"),
					InputType:  strPtr(".trade.RiskRequest"),
					OutputType: strPtr(".trade.RiskResponse"),
				},
			},
		},
	}

	return fd
}

// ---------------------------------------------------------------------------
// init – called once via sync.Once the first time any ProtoReflect() fires
// ---------------------------------------------------------------------------

func file_trade_proto_init() {
	if file_trade_proto_initCalled {
		return
	}
	file_trade_proto_initCalled = true

	// Build raw descriptor bytes from the programmatic FileDescriptorProto.
	fdProto := buildTradeFileDescriptorProto()
	var marshalErr error
	file_trade_proto_rawDesc, marshalErr = goproto.Marshal(fdProto)
	if marshalErr != nil {
		panic("proto: failed to marshal trade.proto FileDescriptorProto: " + marshalErr.Error())
	}

	// Register message types with protoimpl and obtain MessageInfo objects.
	file_trade_proto_desc, _ = protoimpl.X.ExportMessageFile(
		"trade.proto",
		file_trade_proto_rawDesc,
		file_trade_proto_goTypes,
	)

	// Store per-message descriptors.
	msgs := file_trade_proto_desc.Messages()
	for i := range file_trade_proto_msgDescs {
		if i < msgs.Len() {
			file_trade_proto_msgDescs[i] = msgs.Get(i)
		}
	}

	// Resolve cross-message type dependencies from depIdxs.
	// depIdxs format: [msgIdx, fieldNum1, typeIdx1, fieldNum2, typeIdx2, ..., -1, ...]
	//   -1 terminates each message's dep list; mi < 0 means no deps.
	// This wires the headers map field (field 3 of RiskRequest) to HeadersEntry.
	for i := 0; i < len(file_trade_proto_depIdxs); {
		mi := int(file_trade_proto_depIdxs[i])
		i++
		if mi < 0 {
			continue // no deps for this message
		}
		for i < len(file_trade_proto_depIdxs) {
			fn := int(file_trade_proto_depIdxs[i])
			i++
			if fn < 0 {
				break // end of this message's dep list
			}
			ti := int(file_trade_proto_depIdxs[i])
			i++
			// Set the field's message type so the proto codec can serialise
			// map / nested-message fields correctly.
			if mi < len(file_trade_proto_goTypes) && ti < len(file_trade_proto_goTypes) {
				srcMsgInfo := protoimpl.X.MessageInfoOf(file_trade_proto_goTypes[mi])
				if srcMsgInfo != nil {
					fi := srcMsgInfo.Fields.ByNumber(protoreflect.FieldNumber(fn))
					if fi != nil {
						depMsgInfo := protoimpl.X.MessageInfoOf(file_trade_proto_goTypes[ti])
						if depMsgInfo != nil {
							fi.L1.ExportSetMessage(depMsgInfo)
						}
					}
				}
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Tiny helpers for building descriptorpb pointers
// ---------------------------------------------------------------------------

func strPtr(s string) *string                                    { return &s }
func int32Ptr(n int32) *int32                                   { return &n }
func boolPtr(b bool) *bool                                      { return &b }
func typPtr(t descriptorpb.FieldDescriptorProto_Type) *descriptorpb.FieldDescriptorProto_Type       { return &t }
func lblPtr(l descriptorpb.FieldDescriptorProto_Label) *descriptorpb.FieldDescriptorProto_Label     { return &l }

// Keep the reflect import used (needed by protoimpl at link time).
var _ = reflect.TypeOf
