// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: trade.proto
//
// This file was manually written to match the output of protoc-gen-go-grpc v1.3.0.

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Ensure compile-time compatibility with the expected gRPC version.
const _ = grpc.SupportPackageIsVersion7

// ---------------------------------------------------------------------------
// Client interface + implementation
// ---------------------------------------------------------------------------

// RiskCheckClient is the client API for the RiskCheck service.
type RiskCheckClient interface {
	CheckRisk(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error)
}

type riskCheckClient struct {
	cc grpc.ClientConnInterface
}

// NewRiskCheckClient creates a new RiskCheck gRPC client.
func NewRiskCheckClient(cc grpc.ClientConnInterface) RiskCheckClient {
	return &riskCheckClient{cc}
}

func (c *riskCheckClient) CheckRisk(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, "/trade.RiskCheck/CheckRisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ---------------------------------------------------------------------------
// Server interface + unimplemented base
// ---------------------------------------------------------------------------

// RiskCheckServer is the server API for the RiskCheck service.
// All implementations must embed UnimplementedRiskCheckServer for forward
// compatibility.
type RiskCheckServer interface {
	CheckRisk(context.Context, *RiskRequest) (*RiskResponse, error)
	mustEmbedUnimplementedRiskCheckServer()
}

// UnimplementedRiskCheckServer must be embedded to have forward-compatible
// implementations.
type UnimplementedRiskCheckServer struct{}

func (UnimplementedRiskCheckServer) CheckRisk(context.Context, *RiskRequest) (*RiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRisk not implemented")
}
func (UnimplementedRiskCheckServer) mustEmbedUnimplementedRiskCheckServer() {}

// UnsafeRiskCheckServer may be embedded to opt out of forward compatibility.
// Its use is not recommended.
type UnsafeRiskCheckServer interface {
	mustEmbedUnimplementedRiskCheckServer()
}

// ---------------------------------------------------------------------------
// Service registration
// ---------------------------------------------------------------------------

// RegisterRiskCheckServer registers the RiskCheck service implementation with
// the given gRPC server.
func RegisterRiskCheckServer(s grpc.ServiceRegistrar, srv RiskCheckServer) {
	s.RegisterService(&RiskCheck_ServiceDesc, srv)
}

// ---------------------------------------------------------------------------
// gRPC handler functions (used by the server-side ServiceDesc)
// ---------------------------------------------------------------------------

func _RiskCheck_CheckRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskCheckServer).CheckRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trade.RiskCheck/CheckRisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskCheckServer).CheckRisk(ctx, req.(*RiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ---------------------------------------------------------------------------
// Service descriptor
// ---------------------------------------------------------------------------

// RiskCheck_ServiceDesc is the grpc.ServiceDesc for the RiskCheck service.
// It is intended to be used only by generated code and gRPC internals.
var RiskCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trade.RiskCheck",
	HandlerType: (*RiskCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRisk",
			Handler:    _RiskCheck_CheckRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade.proto",
}
