FROM python:3.8-buster
WORKDIR /app
COPY requirements-legacy.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY main-legacy.py ./main.py
EXPOSE 8080
HEALTHCHECK --interval=10s CMD curl -f http://localhost:8080/health || exit 1
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
